/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import server.Position;

/**
 *
 * @author swallak
 */
public class ClientViewer extends javax.swing.JFrame {

    Client client;
    Thread updateFlyPositionT;
    Timer updateGamersT;
    /**
     * Creates new form ClientViewer
     */
//    public ClientViewer(String serverHostName) {
//        initComponents();
//        client = new Client(serverHostName);
//        client.connected = false;
//        fly.setVisible(false);
//    }

    public ClientViewer() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connectPanel = new javax.swing.JPanel();
        userNameField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        playPanel = new javax.swing.JLayeredPane();
        fly = new javax.swing.JLabel();
        gamersPanel = new javax.swing.JScrollPane();
        gamersTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        connectPanel.setMaximumSize(new java.awt.Dimension(160, 124));
        connectPanel.setMinimumSize(new java.awt.Dimension(160, 124));
        connectPanel.setName(""); // NOI18N

        userNameField.setText("username");
        userNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userNameFieldMousePressed(evt);
            }
        });

        loginButton.setText("login");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout connectPanelLayout = new javax.swing.GroupLayout(connectPanel);
        connectPanel.setLayout(connectPanelLayout);
        connectPanelLayout.setHorizontalGroup(
            connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(userNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(loginButton))
                .addContainerGap())
        );
        connectPanelLayout.setVerticalGroup(
            connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/fly-icon.png"))); // NOI18N
        fly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                flyMousePressed(evt);
            }
        });

        playPanel.setLayer(fly, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout playPanelLayout = new javax.swing.GroupLayout(playPanel);
        playPanel.setLayout(playPanelLayout);
        playPanelLayout.setHorizontalGroup(
            playPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playPanelLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(fly)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        playPanelLayout.setVerticalGroup(
            playPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playPanelLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(fly)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        gamersTextArea.setEditable(false);
        gamersTextArea.setColumns(10);
        gamersTextArea.setRows(5);
        gamersPanel.setViewportView(gamersTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(connectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gamersPanel))
                .addGap(10, 10, 10)
                .addComponent(playPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(connectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gamersPanel)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameFieldMousePressed
        //Remove text whenc clicking
        userNameField.setText("");
        //gamersTextArea.append("SAAD\n");
    }//GEN-LAST:event_userNameFieldMousePressed

    private void loginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMousePressed
        // Connection Handeler
        if ("login".equals(loginButton.getText())) {
            client = new Client("localhost");
            client.setMyUserName(userNameField.getText());
            System.out.println("Connection username:" + userNameField.getText());
            boolean status = client.connect();
            //Success full connection.
            if (status) {
                loginButton.setText("logout");
                System.out.println("Login succesful");
                userNameField.setVisible(false);
                fly.setVisible(true);
                client.connected=true;
                client.start();
                startViewer();
            } //Failure to connect
            else {
                System.out.println("Connection failure; Username already used");
                userNameField.setForeground(Color.red);
                userNameField.setText("username is used");
            }
        } else {
            System.out.println("Disconnecting " + client.getMyUserName());
            boolean status = client.disconnect();
            if (status) {
                System.out.println("logout successful");
                userNameField.setText("username");
                userNameField.setForeground(Color.GRAY);
                userNameField.setVisible(true);
                loginButton.setText("login");
                fly.setVisible(false);
                gamersTextArea.setText("");
                client.stop();
                //client = null;
            } else {
                System.out.println("logout failed");
            }
        }
    }//GEN-LAST:event_loginButtonMousePressed

    private void flyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flyMousePressed
        client.huntFly();
    }//GEN-LAST:event_flyMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                //new ClientViewer(args[0]).setVisible(true);
//                new ClientViewer("localhost").setVisible(true);
//            }
//        });
        ClientViewer viewer = new ClientViewer();
        viewer.setVisible(true);

        
        

//        while (true) {
//            Position pos = viewer.client.getFlyPosition();
//            viewer.fly.setLocation(pos.getPosX() % viewer.playPanel.getWidth(), pos.getPosY() % viewer.playPanel.getHeight());
//            System.out.println(pos);
//        }

    }
    public void startViewer() {
        if (client != null) {
            updateFlyPositionT = new Thread(new Runnable() {
                @Override
                public void run() {
                    System.out.println("Starting thread for updating fly position");
                    int x = 0, y = 0;
                    while (true && client != null) {
                        if (client.fly != null) {
                            x = client.fly.getPosX() % (playPanel.getWidth() - 40);
                            y = client.fly.getPosY() % (playPanel.getHeight() - 40);
                        }

                        fly.setLocation(x, y);
                    }

                }
            });
            updateFlyPositionT.start();

            updateGamersT = new Timer();
            updateGamersT.schedule(new TimerTask() {
                @Override
                public void run() {
                    gamersTextArea.setText("");
                    //gamersTextArea.append("swallak\n");
                    if (client.gamers != null) {
                        for (Object g : client.gamers) {
                            gamersTextArea.append(g.toString() + "\n");
                        }
                    }

                }
            }, 0, 2000);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel connectPanel;
    private javax.swing.JLabel fly;
    private javax.swing.JScrollPane gamersPanel;
    private javax.swing.JTextArea gamersTextArea;
    private javax.swing.JButton loginButton;
    private javax.swing.JLayeredPane playPanel;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
